---
title: "Untitled"
author: "Henrique Capatto, Murilo Salgado razoli RA 146406, 150987"
date: "3 de setembro de 2016"
output: html_document
---

#Planejamento e Pesquisa

##Introdução:

Sabemos que ao realizarmos testes de igualdade de médias como também variâncias precisamos que as duas populações sejam independentes. Na pratica não é algo que acontece acontece, em várias situações nossas populações são dependentes.

Realizamos um experimento planejado dentro de aula, do qual se tratava da coleta de informações entre a mão direita e a mão esquerda, onde dois medem o número de cliques em um tempo de 30 segundos atravês de um teste na internet.Primeiramente foi aleatorizado qual mão o individuo iria utilizar primeiro, dado 1- começaria com a mão direita, 0- começaria com a mão esquerda.

Numa situação de comparação entre a mão direita e a mão esquerda, onde dois medem o número de cliques em um tempo de 30 segundos, a medida nesse experimento não são independentes porque vem da mesma unidade. Neste caso, utilizamos o teste $t$ pareado.

##Etapas

**E1:** Coleta das informações de cada individuo sobre a performance de números de cliques em 30 segundos em cada mão.

**E2:** Como variavel resposta foi definido a diferença dos cliques, entre o número de cliques corretos em 30 segundos, sendo primeira observação $X_1,\ldots,X_n$ e segunda observação $Y_1,\ldots,Y_n$.          

**E3:** Realização dos testes.

Queremos a compatibilidade da performance do número de cliques em 30 segundos entre a mão direita e a mão esquerda.

Consideremos duas amostras dependentes $X_1,\ldots,X_n$ e $Y_1,\ldots,Y_n$. Neste caso consideraremos observações pareadas, isto é, podemos considerar que temos na realidade uma amostra de pares $(X_1,Y_1), \ldots, (X_n,Y_n)$. Vamos definir $D_i = X_i-Y_i$, para $i = 1,2,\ldots,n$. Assim obteremos a amostra $D_1,\ldots,D_n$, resultante das diferenças entre os valores de cada par. Aqui, apesar das amostras serem dependentes, vamos considerar que $D_i\sim N(\mu_D,\sigma_D^2)$.

Para realizar o teste $t$ pareado devemos primeiramente estabelecer uma das hipóteses 
$$
\begin{cases}
H_0 = \mu_D  \\
H_1 \neq \mu_D 
\end{cases}	
$$

O parâmetro $\mu_D$ será estimado pela média amostral das diferenças, ou seja, $ \overline{D} $, O parâmetro $\sigma_D^2$ será estimado pela variância amostral das diferenças, ou seja, 

s_D^2=\frac{\sum_{i=1}^n(D_i-\overline{D})^2}{n-1}
$$
O teste será realizado pela expressão 
$$
T=\frac{\overline{D}-\mu_D}{\frac{s_D}{\sqrt{n}}}
$$


```{r, echo = TRUE}

library("ggplot2")

#leitura dos dados
amostra.tab = read.csv(file = file.choose(), header = T)
#dados ordenados por quem começou com a mão direita

comeco_direita=subset(amostra.tab,ordem==1)

#dados ordenados por quem começou com a mão esquerda

comeco_esquerda=subset(amostra.tab,ordem==0)

#Estatística básicas

mi_dif_direta=mean(comeco_direita$dados.d-comeco_direita$dados.e)

mi_dif_esquerda=mean(comeco_esquerda$dados.d-comeco_esquerda$dados.e)

sigma_dif_direta=sd(comeco_direita$dados.d-comeco_direita$dados.e)

sigma_dif_esquerda=sd(comeco_esquerda$dados.d-comeco_esquerda$dados.e)

tabela_estat_bas=data.frame(mi_dif_direta,mi_dif_esquerda,sigma_dif_direta,sigma_dif_esquerda)


shapiro.test(amostra.tab$dados.d)

shapiro.test(amostra.tab$dados.e)

dif = amostra.tab$dados.d - amostra.tab$dados.e

amostra.tab =  data.frame(amostra.tab,dif)

t.test(amostra.tab$dados.d, amostra.tab$dados.e,paired=TRUE)

par = sqrt(20)/(sum((amostra.tab$dif-mean(amostra.tab$dif))^2)/19)

x <- seq(-10,10,0.01)
y <- pt(x,19,ncp=par)

dados <- data.frame(x,y)

g <- ggplot(data=dados,aes(x,y))

g+geom_line(colour="lemonchiffon4",size=1.15)+xlab("Quantis")+ylab("Probabilidades")+ggtitle("Função Poder")+theme_bw()

```